trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# ✅ Install Java 17 using the official Azure Pipelines task
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# ✅ Optional: verify Java version
- script: java -version
  displayName: 'Check Java Version'

# ✅ Maven build
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-X'
    javaHomeOption: 'Path'
    mavenVersionOption: 'Default'
    publishJUnitResults: true
